export const availableLanguages = [
  { code: "au", label: "Australia", flag: "🇦🇺" },
  { code: "ca", label: "Canada", flag: "🇨🇦" },
  { code: "de", label: "Germany", flag: "🇩🇪" },
  { code: "ie", label: "Ireland", flag: "🇮🇪" },
  { code: "nz", label: "New Zealand", flag: "🇳🇿" },
  { code: "no", label: "Norway", flag: "🇳🇴" },
  { code: "fi", label: "Finland", flag: "🇫🇮" },
  { code: "at", label: "Austria", flag: "🇦🇹" },
  { code: "ch", label: "Switzerland", flag: "🇨🇭" },
  { code: "dk", label: "Denmark", flag: "🇩🇰" },
  { code: "fr", label: "France", flag: "🇫🇷" },
  { code: "it", label: "Italy", flag: "🇮🇹" },
  { code: "pl", label: "Poland", flag: "🇵🇱" },
  { code: "se", label: "Sweden", flag: "🇸🇪" },
  { code: "cz", label: "Czech", flag: "🇨🇿" },
  { code: "sk", label: "Slovakia", flag: "🇸🇰" },
  { code: "be", label: "Belgium", flag: "🇧🇪" },
  { code: "gr", label: "Greece", flag: "🇬🇷" },
  { code: "nl", label: "Netherlands", flag: "🇳🇱" },
  { code: "hu", label: "Hungary", flag: "🇭🇺" },
  { code: "bg", label: "Bulgaria", flag: "🇧🇬" },
  { code: "all", label: "World", flag: "🌍" }
];
export const availableLanguages1039 = [
  { code: "au", label: "Australia", flag: "🇦🇺" },
  { code: "at", label: "Austria", flag: "🇦🇹" },
  { code: "be", label: "Belgium", flag: "🇧🇪" },
  { code: "bg", label: "Bulgaria", flag: "🇧🇬" },
  { code: "ca", label: "Canada", flag: "🇨🇦" },
  { code: "cz", label: "Czech", flag: "🇨🇿" },
  { code: "dk", label: "Denmark", flag: "🇩🇰" },
  { code: "fi", label: "Finland", flag: "🇫🇮" },
  { code: "fr", label: "France", flag: "🇫🇷" },
  { code: "de", label: "Germany", flag: "🇩🇪" },
  { code: "gr", label: "Greece", flag: "🇬🇷" },
  { code: "hu", label: "Hungary", flag: "🇭🇺" },
  { code: "ie", label: "Ireland", flag: "🇮🇪" },
  { code: "it", label: "Italy", flag: "🇮🇹" },
  { code: "nl", label: "Netherlands", flag: "🇳🇱" },
  { code: "nz", label: "New Zealand", flag: "🇳🇿" },
  { code: "no", label: "Norway", flag: "🇳🇴" },
  { code: "pl", label: "Poland", flag: "🇵🇱" },
  { code: "pt", label: "Portugal", flag: "🇵🇹" },
  { code: "sk", label: "Slovakia", flag: "🇸🇰" },
  { code: "es", label: "Spain", flag: "🇪🇸" },
  { code: "se", label: "Sweden", flag: "🇸🇪" },
  { code: "ch", label: "Switzerland", flag: "🇨🇭" },
  { code: "tr", label: "Turkey", flag: "🇹🇷" },
  { code: "gb", label: "United Kingdom", flag: "🇬🇧" },
  { code: "all", label: "World", flag: "🌍" },
];
export const availableLanguages1043 = [
  { code: "ca", label: "Canada", flag: "🇨🇦" },
  { code: "us", label: "United States", flag: "🇺🇸" },
];
export const availableLanguages1044 = [
  { code: "au", label: "Australia", flag: "🇦🇺" },
  { code: "at", label: "Austria", flag: "🇦🇹" },
  { code: "be", label: "Belgium", flag: "🇧🇪" },
  { code: "ca", label: "Canada", flag: "🇨🇦" },
  { code: "ch", label: "Switzerland", flag: "🇨🇭" },
  { code: "nl", label: "Netherlands", flag: "🇳🇱" },
  { code: "de", label: "Germany", flag: "🇩🇪" },
  { code: "gr", label: "Greece", flag: "🇬🇷" },
  { code: "cz", label: "The Czech Republic", flag: "🇨🇿" },
  { code: "fi", label: "Finland", flag: "🇫🇮" },
  { code: "gb", label: "Great Britain", flag: "🇬🇧" },
  { code: "ie", label: "Ireland", flag: "🇮🇪" },
  { code: "it", label: "Italy", flag: "🇮🇹" },
  { code: "nz", label: "New Zealand", flag: "🇳🇿" },
  { code: "no", label: "Norway", flag: "🇳🇴" },
  { code: "pl", label: "Poland", flag: "🇵🇱" },
  { code: "za", label: "South Africa", flag: "🇿🇦" },
  { code: "se", label: "Sweden", flag: "🇸🇪" },
  { code: "us", label: "USA", flag: "🇺🇸" },
  { code: "all", label: "World", flag: "🌍" },
];

export const availableLanguagesCLD_VIP = [
  { code: "au", label: "Australia", flag: "🇦🇺" },
  { code: "at", label: "Austria", flag: "🇦🇹" },
  { code: "be", label: "Belgium", flag: "🇧🇪" },
  { code: "ca", label: "Canada", flag: "🇨🇦" },
  { code: "ch", label: "Switzerland", flag: "🇨🇭" },
  { code: "cz", label: "The Czech Republic", flag: "🇨🇿" },
  { code: "de", label: "Germany", flag: "🇩🇪" },
  { code: "dk", label: "Denmark", flag: "🇩🇰" },
  { code: "fi", label: "Finland", flag: "🇫🇮" },
  { code: "fr", label: "France", flag: "🇫🇷" },
  { code: "gr", label: "Greece", flag: "🇬🇷" },
  { code: "hu", label: "Hungary", flag: "🇭🇺" },
  { code: "ie", label: "Ireland", flag: "🇮🇪" },
  { code: "it", label: "Italy", flag: "🇮🇹" },
  { code: "no", label: "Norway", flag: "🇳🇴" },
  { code: "nz", label: "New Zealand", flag: "🇳🇿" },
  { code: "pl", label: "Poland", flag: "🇵🇱" },
  { code: "se", label: "Sweden", flag: "🇸🇪" },
  { code: "sk", label: "Slovakia", flag: "🇸🇰" },
  { code: "all", label: "World", flag: "🌍" },
];
